[tool.poetry]
name = "bachelor"
version = "0.1.0"
description = ""
authors = ["marcsikor <s223464@student.uek.krakow.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
